create table if not exists public.leads2 (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  whatsapp text not null,
  whatsapp_digits text not null,
  source_page text not null default 'page-guilherme-v4',
  event_name text not null default 'checkout_intent',
  cta_label text,
  checkout_url text,
  page_path text,
  referrer text,
  user_agent text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text
);

create index if not exists leads2_created_at_idx on public.leads2 (created_at desc);
create index if not exists leads2_email_idx on public.leads2 (email);
create index if not exists leads2_whatsapp_digits_idx on public.leads2 (whatsapp_digits);

alter table public.leads2 enable row level security;

drop policy if exists "public_can_insert_leads2" on public.leads2;
create policy "public_can_insert_leads2"
on public.leads2
for insert
to anon, authenticated
with check (true);

